# Generated by Django 4.0.4 on 2022-05-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CocreteStudent',
            new_name='ConcreteStudent',
        ),
    ]
